COUNTY_NAME: SanFrancisco
DATA_TYPE: Cases

REQUEST:
  TYPE: POST
  URL: https://wabi-us-gov-iowa-api.analysis.usgovcloudapi.net/public/reports/querydata?synchronous=true
  HEADERS:
    Accept: application/json, text/plain, */*
    Accept-Encoding: gzip, deflate, br
    Accept-Language: en-US,en;q=0.9
    ActivityId: 92ab9535-b7d3-477b-adbb-eb163a4b24e9
    Connection: keep-alive
    Content-Length: 1815
    Content-Type: application/json;charset=UTF-8
    Host: wabi-us-gov-iowa-api.analysis.usgovcloudapi.net
    Origin: https://app.powerbigov.us
    Referer: https://app.powerbigov.us/view?r=eyJrIjoiMWEyYTRhYTAtMTdjYi00YTE1LWJiMTQtYTY3NmJmMjJhOThkIiwidCI6IjIyZDVjMmNmLWNlM2UtNDQzZC05YTdmLWRmY2MwMjMxZjczZiJ9&navContentPaneEnabled=false&filterPaneEnabled=false
    RequestId: b82a0201-b443-b44d-a6b6-55c10bdf7971
    Sec-Fetch-Dest: empty
    Sec-Fetch-Mode: cors
    Sec-Fetch-Site: cross-site
    User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
    X-PowerBI-ResourceKey: 1a2a4aa0-17cb-4a15-bb14-a676bf22a98d
  PAYLOAD: {"version":"1.0.0","queries":[{"Query":{"Commands":[{"SemanticQueryDataShapeCommand":{"Query":{"Version":2,"From":[{"Name":"d1","Entity":"Deaths_Ethnicity"}],"Select":[{"Aggregation":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"d1"}},"Property":"Total Cases"}},"Function":0},"Name":"Sum(Deaths_Ethnicity.Total Cases)"},{"Column":{"Expression":{"SourceRef":{"Source":"d1"}},"Property":"raceethnicity"},"Name":"Deaths_Ethnicity.raceethnicity"}],"OrderBy":[{"Direction":1,"Expression":{"Aggregation":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"d1"}},"Property":"Total Cases"}},"Function":0}}}]},"Binding":{"Primary":{"Groupings":[{"Projections":[0,1]}]},"DataReduction":{"DataVolume":4,"Primary":{"Window":{"Count":1000}}},"Version":1}}}]},"CacheKey":"{\"Commands\":[{\"SemanticQueryDataShapeCommand\":{\"Query\":{\"Version\":2,\"From\":[{\"Name\":\"d1\",\"Entity\":\"Deaths_Ethnicity\"}],\"Select\":[{\"Aggregation\":{\"Expression\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"d1\"}},\"Property\":\"Total Cases\"}},\"Function\":0},\"Name\":\"Sum(Deaths_Ethnicity.Total Cases)\"},{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"d1\"}},\"Property\":\"raceethnicity\"},\"Name\":\"Deaths_Ethnicity.raceethnicity\"}],\"OrderBy\":[{\"Direction\":1,\"Expression\":{\"Aggregation\":{\"Expression\":{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"d1\"}},\"Property\":\"Total Cases\"}},\"Function\":0}}}]},\"Binding\":{\"Primary\":{\"Groupings\":[{\"Projections\":[0,1]}]},\"DataReduction\":{\"DataVolume\":4,\"Primary\":{\"Window\":{\"Count\":1000}}},\"Version\":1}}}]}","QueryId":"","ApplicationContext":{"DatasetId":"507f48cb-a9bd-432f-af06-de81cb290a5e","Sources":[{"ReportId":"4b76105e-31ab-44bf-89d7-66a4323e3e02"}]}}],"cancelQueries":[],"modelId":282807},
