DATES:
  '2020-06-14':
    UNKNOWN_DEATHS:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 0
      - DM0
      - 0
      - C
      - 1
    BLACK_DEATHS:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 0
      - DM0
      - 1
      - C
      - 1
    HISPANIC_DEATHS:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 0
      - DM0
      - 2
      - C
      - 1
    WHITE_DEATHS:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 0
      - DM0
      - 3
      - C
      - 1
    ASIAN_DEATHS:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 0
      - DM0
      - 4
      - C
      - 1
  '2020-07-20':
    UNKNOWN_DEATHS:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 0
      - DM0
      - 0
      - C
      - 1
    BLACK_DEATHS:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 0
      - DM0
      - 1
      - C
      - 1
    HISPANIC_DEATHS:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 0
      - DM0
      - 3
      - C
      - 1
    WHITE_DEATHS:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 0
      - DM0
      - 2
      - C
      - 1
    ASIAN_DEATHS:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 0
      - DM0
      - 4
      - C
      - 1
  '2020-07-24':
    BLACK_DEATHS:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 0
      - DM0
      - 0
      - C
      - 1
    HISPANIC_DEATHS:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 0
      - DM0
      - 2
      - C
      - 1
    WHITE_DEATHS:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 0
      - DM0
      - 1
      - C
      - 1
    ASIAN_DEATHS:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 0
      - DM0
      - 3
      - C
      - 1
  '2020-07-28':
    UNKNOWN_DEATHS:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 0
      - DM0
      - 0
      - C
      - 1
    BLACK_DEATHS:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 0
      - DM0
      - 1
      - C
      - 1
    HISPANIC_DEATHS:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 0
      - DM0
      - 3
      - C
      - 1
    WHITE_DEATHS:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 0
      - DM0
      - 2
      - C
      - 1
    ASIAN_DEATHS:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 0
      - DM0
      - 4
      - C
      - 1
  '2020-08-06':
    MULTI_RACE_DEATHS:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 0
      - DM0
      - 0
      - C
      - 1
    UNKNOWN_DEATHS:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 0
      - DM0
      - 1
      - C
      - 1
    BLACK_DEATHS:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 0
      - DM0
      - 2
      - C
      - 1
    HISPANIC_DEATHS:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 0
      - DM0
      - 4
      - C
      - 1
    WHITE_DEATHS:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 0
      - DM0
      - 3
      - C
      - 1
    ASIAN_DEATHS:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 0
      - DM0
      - 5
      - C
      - 1