NAME: Kern
DATA_TYPE: Cases

REQUEST:
  TYPE: POST
  URL: https://wabi-us-gov-iowa-api.analysis.usgovcloudapi.net/public/reports/querydata?synchronous=true
  HEADERS:
    Accept: application/json, text/plain, */*
    Accept-Encoding: gzip, deflate, br
    Accept-Language: en-US,en;q=0.9
    ActivityId: 3a2b9b3d-a1c0-422f-97a7-ec30fa14e82e
    Connection: keep-alive
    Content-Length: '2193'
    Content-Type: application/json;charset=UTF-8
    Host: wabi-us-gov-iowa-api.analysis.usgovcloudapi.net
    Origin: https://app.powerbigov.us
    Referer: https://app.powerbigov.us/view?r=eyJrIjoiNDg0ZmE3MjgtZDg0OC00N2QxLWE4ZWQtOGNkZDFhYWM3ZTlmIiwidCI6ImUwZjJlNGI1LTA1MTUtNDAyOC05OWYyLTJlN2E0M2ZlNTM3OSJ9
    RequestId: 29fb4bb9-0676-8f67-eff8-3df9215eca51
    Sec-Fetch-Dest: empty
    Sec-Fetch-Mode: cors
    Sec-Fetch-Site: cross-site
    User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
    X-PowerBI-ResourceKey: 0a717c4e-b7f5-4efd-be28-64908f9e0f18
  PAYLOAD: {"version":"1.0.0","queries":[{"Query":{"Commands":[{"SemanticQueryDataShapeCommand":{"Query":{"Version":2,"From":[{"Name":"n","Entity":"nCoV Condition","Type":0}],"Select":[{"Column":{"Expression":{"SourceRef":{"Source":"n"}},"Property":"nCoV17"},"Name":"nCoV Condition.nCoV17"},{"Measure":{"Expression":{"SourceRef":{"Source":"n"}},"Property":"CurrentCaseCount"},"Name":"nCoV Condition.CurrentCaseCount"}],"Where":[{"Condition":{"Not":{"Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"n"}},"Property":"AgeGroup"}}],"Values":[[{"Literal":{"Value":"null"}}]]}}}}},{"Condition":{"Not":{"Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"n"}},"Property":"Region"}}],"Values":[[{"Literal":{"Value":"'Check Address'"}}],[{"Literal":{"Value":"null"}}]]}}}}},{"Condition":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"n"}},"Property":"nCoV11"}}],"Values":[[{"Literal":{"Value":"'Female'"}}],[{"Literal":{"Value":"'Male'"}}]]}}}]},"Binding":{"Primary":{"Groupings":[{"Projections":[0,1]}]},"DataReduction":{"DataVolume":3,"Primary":{"Top":{}}},"Version":1},"ExecutionMetricsKind":3}}]},"QueryId":"","ApplicationContext":{"DatasetId":"d38b9ca5-7d07-482d-a458-9e6f1d5a43cb","Sources":[{"ReportId":"690ff3cf-5b9d-47de-86c7-45d6e548acb2"}]}}],"cancelQueries":[],"modelId":286040}