ROOT: https://api.census.gov/data/2018/acs/acs5/subject?
REGION:
  - for=county:067
  - in=state:06

METADATA:
  HOUSEHOLD_MEDIAN_INCOME_DOLLARS:
    TOTAL: S1903_C03_010E
    WHITE: S1903_C03_002E
    BLACK: S1903_C03_003E
    AMERICAN_INDIAN_ALASKA_NATIVES: S1903_C03_004E
    ASIAN: S1903_C03_005E
    NATIVE_HAWAIIAN_PACIFIC_ISLANDER: S1903_C03_006E
    OTHER: S1903_C03_007E
    MULTI_RACE: S1903_C03_008E
    HISPANIC: S1903_C03_009E
  HIGH_SCHOOL_GRADUATE_OR_HIGHER_25_PLUS_TOTAL:
    TOTAL: S1501_C01_014E
    WHITE: S1501_C01_032E
    BLACK: S1501_C01_035E
    AMERICAN_INDIAN_ALASKA_NATIVES: S1501_C01_038E
    ASIAN: S1501_C01_041E
    NATIVE_HAWAIIAN_PACIFIC_ISLANDER: S1501_C01_044E
    OTHER: S1501_C01_047E
    MULTI_RACE: S1501_C01_050E
    HISPANIC: S1501_C01_053E
  BACHELOR_DEGREE_OR_HIGHER_25_PLUS_TOTAL:
    TOTAL: S1501_C01_015E
    WHITE: S1501_C01_033E
    BLACK: S1501_C01_036E
    AMERICAN_INDIAN_ALASKA_NATIVES: S1501_C01_039E
    ASIAN: S1501_C01_042E
    NATIVE_HAWAIIAN_PACIFIC_ISLANDER: S1501_C01_045E
    OTHER: S1501_C01_048E
    MULTI_RACE: S1501_C01_051E
    HISPANIC: S1501_C01_054E
  PUBLIC_TRANSPORTATION:
    TOTAL: S0802_C04_001E
    WHITE: S0802_C04_020E
    BLACK: S0802_C04_013E
    AMERICAN_INDIAN_ALASKA_NATIVES: S0802_C04_014E
    ASIAN: S0802_C04_015E
    NATIVE_HAWAIIAN_PACIFIC_ISLANDER: S0802_C04_016E
    OTHER: S0802_C04_017E
    MULTI_RACE: S0802_C04_018E
    HISPANIC: S0802_C04_019E
  CAR_TRUCK_VAN_ALONE:
    TOTAL: S0804_C02_001E
    WHITE: S0804_C02_020E
    BLACK: S0804_C02_013E
    AMERICAN_INDIAN_ALASKA_NATIVES: S0804_C02_014E
    ASIAN: S0804_C02_015E
    NATIVE_HAWAIIAN_PACIFIC_ISLANDER: S0804_C02_016E
    OTHER: S0804_C02_017E
    MULTI_RACE: S0804_C02_018E
    HISPANIC: S0804_C02_019E
  CAR_TRUCK_VAN_CARPOOL:
    TOTAL: S0804_C03_001E
    WHITE: S0804_C03_020E
    BLACK: S0804_C03_013E
    AMERICAN_INDIAN_ALASKA_NATIVES: S0804_C03_014E
    ASIAN: S0804_C03_015E
    NATIVE_HAWAIIAN_PACIFIC_ISLANDER: S0804_C03_016E
    OTHER: S0804_C03_017E
    MULTI_RACE: S0804_C03_018E
    HISPANIC: S0804_C03_019E






