ROOT: https://api.census.gov/data/2018/acs/acs5/subject?
REGION:
  - for=county:067
  - in=state:06

METADATA:
  HOUSEHOLD_MEDIAN_INCOME_DOLLARS:
    Total: S1903_C03_010E
    White: S1903_C03_002E
    Black: S1903_C03_003E
    American Indian/Alaska Native: S1903_C03_004E
    Asian: S1903_C03_005E
    Native Hawaiian/Pacific Islander: S1903_C03_006E
    Multi-Race: S1903_C03_008E
    Hispanic: S1903_C03_009E
  HIGH_SCHOOL_GRADUATE_OR_HIGHER_25_PLUS_TOTAL:
    Total: S1501_C01_014E
    White: S1501_C01_032E
    Black: S1501_C01_035E
    American Indian/Alaska Native: S1501_C01_038E
    Asian: S1501_C01_041E
    Native Hawaiian/Pacific Islander: S1501_C01_044E
    Multi-Race: S1501_C01_050E
    Hispanic: S1501_C01_053E
  BACHELOR_DEGREE_OR_HIGHER_25_PLUS_TOTAL:
    Total: S1501_C01_015E
    White: S1501_C01_033E
    Black: S1501_C01_036E
    American Indian/Alaska Native: S1501_C01_039E
    Asian: S1501_C01_042E
    Native Hawaiian/Pacific Islander: S1501_C01_045E
    Multi-Race: S1501_C01_051E
    Hispanic: S1501_C01_054E
  PUBLIC_TRANSPORTATION:
    Total: S0802_C04_001E
    White: S0802_C04_020E
    Black: S0802_C04_013E
    American Indian/Alaska Native: S0802_C04_014E
    Asian: S0802_C04_015E
    Native Hawaiian/Pacific Islander: S0802_C04_016E
    Multi-Race: S0802_C04_018E
    Hispanic: S0802_C04_019E
  CAR_TRUCK_VAN_ALONE:
    Total: S0804_C02_001E
    White: S0804_C02_020E
    Black: S0804_C02_013E
    American Indian/Alaska Native: S0804_C02_014E
    Asian: S0804_C02_015E
    Native Hawaiian/Pacific Islander: S0804_C02_016E
    Multi-Race: S0804_C02_018E
    Hispanic: S0804_C02_019E
  CAR_TRUCK_VAN_CARPOOL:
    Total: S0804_C03_001E
    White: S0804_C03_020E
    Black: S0804_C03_013E
    American Indian/Alaska Native: S0804_C03_014E
    Asian: S0804_C03_015E
    Native Hawaiian/Pacific Islander: S0804_C03_016E
    Multi-Race: S0804_C03_018E
    Hispanic: S0804_C03_019E

PROCESS_FUNC:
  HOUSEHOLD_MEDIAN_INCOME_DOLLARS: identity
  HIGH_SCHOOL_GRADUATE_OR_HIGHER_25_PLUS_TOTAL: total_per_1000
  BACHELOR_DEGREE_OR_HIGHER_25_PLUS_TOTAL: total_per_1000
  PUBLIC_TRANSPORTATION: perc_of_total_per_1000
  CAR_TRUCK_VAN_ALONE: perc_of_total_per_1000
  CAR_TRUCK_VAN_CARPOOL: perc_of_total_per_1000

HEADERS:
  User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0

API_KEY: 96f7afdb49598b06bb6c3bf1f19a0255c8673f0c