NAME: Sacramento
DATA_TYPE: Cases

REQUEST:
  TYPE: GET
  URL: https://services6.arcgis.com/yeTSZ1znt7H7iDG7/arcgis/rest/services/COVID19_Race_Ethnicity/FeatureServer/0/query?f=json&where=1%3D1&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&orderByFields=Percent_%20desc&resultOffset=0&resultRecordCount=20&resultType=standard&cacheHint=true
  HEADERS: None
  PAYLOAD: None