DATES:
  '2020-06-14':
    BLACK_CASES:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 1
      - DM1
      - 0
      - C
      - 1
    ASIAN_CASES:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 1
      - DM1
      - 1
      - C
      - 1
    HISPANIC_CASES:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 1
      - DM1
      - 2
      - C
      - 1
    NATIVE_HAWAIIAN_PACIFIC_ISLANDER_CASES:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 1
      - DM1
      - 3
      - C
      - 1
    OTHER_CASES:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 1
      - DM1
      - 4
      - C
      - 1
    UNKNOWN_CASES:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 1
      - DM1
      - 5
      - C
      - 1
    WHITE_CASES:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 1
      - DM1
      - 6
      - C
      - 1
  '2020-07-06':
    BLACK_CASES:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 0
      - DM0
      - 0
      - C
      - 1
    ASIAN_CASES:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 0
      - DM0
      - 1
      - C
      - 1
    HISPANIC_CASES:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 0
      - DM0
      - 2
      - C
      - 1
    NATIVE_HAWAIIAN_PACIFIC_ISLANDER_CASES:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 0
      - DM0
      - 3
      - C
      - 1
    OTHER_CASES:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 0
      - DM0
      - 4
      - C
      - 1
    UNKNOWN_CASES:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 0
      - DM0
      - 5
      - C
      - 1
    WHITE_CASES:
      - results
      - 0
      - result
      - data
      - dsr
      - DS
      - 0
      - PH
      - 0
      - DM0
      - 6
      - C
      - 1







