NAME: Riverside
DATA_TYPE: Cases

REQUEST:
  TYPE: GET
  URL: https://services1.arcgis.com/pWmBUdSlVpXStHU6/arcgis/rest/services/COVID19_Race_Graph/FeatureServer/0/query?f=json&where=Race%20NOT%20IN(%27Unknown%27)%20AND%20Race%20NOT%20IN(%27Total%20Pop%27)&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&orderByFields=Rate_100K%20asc&outSR=102100&resultOffset=0&resultRecordCount=32000&resultType=standard&cacheHint=true
  HEADERS: None
  PAYLOAD: None