NAME: LosAngeles
DATA_TYPE: All

REQUEST:
  TYPE: GET
  URL: http://publichealth.lacounty.gov/media/Coronavirus/locations.htm
  HEADERS:
    User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0
  PAYLOAD: None

WEBSITE: http://publichealth.lacounty.gov/media/Coronavirus/locations.htm