REGION_LEVEL: True
ROOT: https://api.census.gov/data/2018/acs/acs5/subject?
REGION:
  - for=county:037
  - in=state:06

METADATA:
  HOUSEHOLD_MEDIAN_INCOME_DOLLARS_OVERALL: S1903_C03_010E
  HIGH_SCHOOL_GRADUATE_OR_HIGHER_25_PLUS_TOTAL_OVERALL: S1501_C01_014E
  BACHELOR_DEGREE_OR_HIGHER_25_PLUS_TOTAL_OVERALL: S1501_C01_015E
  PUBLIC_TRANSPORTATION_OVERALL: S0802_C04_001E
  CAR_TRUCK_VAN_ALONE_OVERALL: S0804_C02_001E
  CAR_TRUCK_VAN_CARPOOL_OVERALL: S0804_C03_001E
  PERCENT_INSURED_OVERALL: S2701_C03_001E
  BELOW_POVERTY_LEVEL_OVERALL: S1701_C02_001E
  POPULATION_GENDER_MALE: S0101_C03_001E
  POPULATION_GENDER_FEMALE: S0101_C05_001E
  EMPLOYED_POPULATION_CHARACTERISTICS_OVERALL: S0501_C01_056E
  EMPLOYED_POPULATION_CHARACTERISTICS_Private_Wage_Salary: S0501_C01_057E
  EMPLOYED_POPULATION_CHARACTERISTICS_Government: S0501_C01_058E
  EMPLOYED_POPULATION_CHARACTERISTICS_Self Employed: S0501_C01_059E
  EMPLOYED_POPULATION_CHARACTERISTICS_Unpaid Family: S0501_C01_060E
  EMPLOYED_POPULATION_CHARACTERISTICS_Management Business: S0501_C01_061E
  EMPLOYED_POPULATION_CHARACTERISTICS_Service Occupations: S0501_C01_062E
  EMPLOYED_POPULATION_CHARACTERISTICS_Sales: S0501_C01_063E
  EMPLOYED_POPULATION_CHARACTERISTICS_Natural Resources: S0501_C01_064E
  EMPLOYED_POPULATION_CHARACTERISTICS_Production: S0501_C01_065E
  EMPLOYED_POPULATION_CHARACTERISTICS_Agricilture: S0501_C01_066E
  EMPLOYED_POPULATION_CHARACTERISTICS_Construction: S0501_C01_067E
  EMPLOYED_POPULATION_CHARACTERISTICS_Manufacturing: S0501_C01_068E
  EMPLOYED_POPULATION_CHARACTERISTICS_Wholesale_Trade: S0501_C01_069E
  EMPLOYED_POPULATION_CHARACTERISTICS_Retail: S0501_C01_070E
  EMPLOYED_POPULATION_CHARACTERISTICS_Transportation: S0501_C01_071E
  EMPLOYED_POPULATION_CHARACTERISTICS_Information: S0501_C01_072E
  EMPLOYED_POPULATION_CHARACTERISTICS_Finance_and_Insurance: S0501_C01_073E
  EMPLOYED_POPULATION_CHARACTERISTICS_Professional_Scientific_and_Management: S0501_C01_074E
  EMPLOYED_POPULATION_CHARACTERISTICS_Educational_Services_and_Health_Care: S0501_C01_075E
  EMPLOYED_POPULATION_CHARACTERISTICS_Arts_Entertainment_and_Recreation: S0501_C01_076E
  EMPLOYED_POPULATION_CHARACTERISTICS_Other: S0501_C01_077E
  EMPLOYED_POPULATION_CHARACTERISTICS_Public_Administration: S0501_C01_078E

PROCESS_FUNC:
  HOUSEHOLD_MEDIAN_INCOME_DOLLARS: identity
  HIGH_SCHOOL_GRADUATE_OR_HIGHER_25_PLUS_TOTAL_OVERALL: total_per_1000
  BACHELOR_DEGREE_OR_HIGHER_25_PLUS_TOTAL_OVERALL: total_per_1000
  PUBLIC_TRANSPORTATION_OVERALL: total_per_1000
  CAR_TRUCK_VAN_ALONE_OVERALL: total_per_1000
  CAR_TRUCK_VAN_CARPOOL_OVERALL: total_per_1000
  PERCENT_INSURED_OVERALL: identity
  BELOW_POVERTY_LEVEL_OVERALL: total_per_1000
  POPULATION_GENDER_MALE: total_per_1000
  POPULATION_GENDER_FEMALE: total_per_1000
  EMPLOYED_POPULATION_CHARACTERISTICS_OVERALL: total_per_1000
  EMPLOYED_POPULATION_CHARACTERISTICS_Private_Wage_Salary: identity
  EMPLOYED_POPULATION_CHARACTERISTICS_Government: identity
  EMPLOYED_POPULATION_CHARACTERISTICS_Self Employed: identity
  EMPLOYED_POPULATION_CHARACTERISTICS_Unpaid Family: identity
  EMPLOYED_POPULATION_CHARACTERISTICS_Management Business: identity
  EMPLOYED_POPULATION_CHARACTERISTICS_Service Occupations: identity
  EMPLOYED_POPULATION_CHARACTERISTICS_Sales: identity
  EMPLOYED_POPULATION_CHARACTERISTICS_Natural Resources: identity
  EMPLOYED_POPULATION_CHARACTERISTICS_Production: identity
  EMPLOYED_POPULATION_CHARACTERISTICS_Agricilture: identity
  EMPLOYED_POPULATION_CHARACTERISTICS_Construction: identity
  EMPLOYED_POPULATION_CHARACTERISTICS_Manufacturing: identity
  EMPLOYED_POPULATION_CHARACTERISTICS_Wholesale_Trade: identity
  EMPLOYED_POPULATION_CHARACTERISTICS_Retail: identity
  EMPLOYED_POPULATION_CHARACTERISTICS_Transportation: identity
  EMPLOYED_POPULATION_CHARACTERISTICS_Information: identity
  EMPLOYED_POPULATION_CHARACTERISTICS_Finance_and_Insurance: identity
  EMPLOYED_POPULATION_CHARACTERISTICS_Professional_Scientific_and_Management: identity
  EMPLOYED_POPULATION_CHARACTERISTICS_Educational_Services_and_Health_Care: identity
  EMPLOYED_POPULATION_CHARACTERISTICS_Arts_Entertainment_and_Recreation: identity
  EMPLOYED_POPULATION_CHARACTERISTICS_Other: identity
  EMPLOYED_POPULATION_CHARACTERISTICS_Public_Administration: identity



HEADERS:
  User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0

API_KEY: 96f7afdb49598b06bb6c3bf1f19a0255c8673f0c