DATES:
  '2020-06-14':
    AMERICAN_INDIAN_OR_ALASKA_NATIVE_CASES: /html/body/div[2]/div[2]/div[3]/table/tbody/tr[25]/td[2]
    AMERICAN_INDIAN_OR_ALASKA_NATIVE_DEATHS: /html/body/div[2]/div[2]/div[3]/table/tbody/tr[39]/td[2]
    ASIAN_CASES: /html/body/div[2]/div[2]/div[3]/table/tbody/tr[26]/td[2]
    ASIAN_DEATHS: /html/body/div[2]/div[2]/div[3]/table/tbody/tr[40]/td[2]
    BLACK_CASES: /html/body/div[2]/div[2]/div[3]/table/tbody/tr[27]/td[2]
    BLACK_DEATHS: /html/body/div[2]/div[2]/div[3]/table/tbody/tr[41]/td[2]
    HISPANIC_CASES: /html/body/div[2]/div[2]/div[3]/table/tbody/tr[28]/td[2]
    HISPANIC_DEATHS: /html/body/div[2]/div[2]/div[3]/table/tbody/tr[42]/td[2]
    NATIVE_HAWAIIAN_PACIFIC_ISLANDER_CASES: /html/body/div[2]/div[2]/div[3]/table/tbody/tr[29]/td[2]
    NATIVE_HAWAIIAN_PACIFIC_ISLANDER_DEATHS: /html/body/div[2]/div[2]/div[3]/table/tbody/tr[43]/td[2]
    WHITE_CASES: /html/body/div[2]/div[2]/div[3]/table/tbody/tr[30]/td[2]
    WHITE_DEATHS: /html/body/div[2]/div[2]/div[3]/table/tbody/tr[44]/td[2]
    OTHER_CASES: /html/body/div[2]/div[2]/div[3]/table/tbody/tr[31]/td[2]
    OTHER_DEATHS: /html/body/div[2]/div[2]/div[3]/table/tbody/tr[45]/td[2]
  '2020-07-02':
    AMERICAN_INDIAN_OR_ALASKA_NATIVE_CASES: /html/body/div[2]/div[3]/div[3]/table/tbody/tr[25]/td[2]
    AMERICAN_INDIAN_OR_ALASKA_NATIVE_DEATHS: /html/body/div[2]/div[3]/div[3]/table/tbody/tr[39]/td[2]
    ASIAN_CASES: /html/body/div[2]/div[3]/div[3]/table/tbody/tr[26]/td[2]
    ASIAN_DEATHS: /html/body/div[2]/div[3]/div[3]/table/tbody/tr[40]/td[2]
    BLACK_CASES: /html/body/div[2]/div[3]/div[3]/table/tbody/tr[27]/td[2]
    BLACK_DEATHS: /html/body/div[2]/div[3]/div[3]/table/tbody/tr[41]/td[2]
    HISPANIC_CASES: /html/body/div[2]/div[3]/div[3]/table/tbody/tr[28]/td[2]
    HISPANIC_DEATHS: /html/body/div[2]/div[3]/div[3]/table/tbody/tr[42]/td[2]
    NATIVE_HAWAIIAN_PACIFIC_ISLANDER_CASES: /html/body/div[2]/div[3]/div[3]/table/tbody/tr[29]/td[2]
    NATIVE_HAWAIIAN_PACIFIC_ISLANDER_DEATHS: /html/body/div[2]/div[3]/div[3]/table/tbody/tr[43]/td[2]
    WHITE_CASES: /html/body/div[2]/div[3]/div[3]/table/tbody/tr[30]/td[2]
    WHITE_DEATHS: /html/body/div[2]/div[3]/div[3]/table/tbody/tr[44]/td[2]
    OTHER_CASES: /html/body/div[2]/div[3]/div[3]/table/tbody/tr[31]/td[2]
    OTHER_DEATHS: /html/body/div[2]/div[3]/div[3]/table/tbody/tr[45]/td[2]
  '2020-07-06':
    AMERICAN_INDIAN_OR_ALASKA_NATIVE_CASES: /html/body/div[2]/div[2]/div[3]/table/tbody/tr[25]/td[2]
    AMERICAN_INDIAN_OR_ALASKA_NATIVE_DEATHS: /html/body/div[2]/div[2]/div[3]/table/tbody/tr[39]/td[2]
    ASIAN_CASES: /html/body/div[2]/div[2]/div[3]/table/tbody/tr[26]/td[2]
    ASIAN_DEATHS: /html/body/div[2]/div[2]/div[3]/table/tbody/tr[40]/td[2]
    BLACK_CASES: /html/body/div[2]/div[2]/div[3]/table/tbody/tr[27]/td[2]
    BLACK_DEATHS: /html/body/div[2]/div[2]/div[3]/table/tbody/tr[41]/td[2]
    HISPANIC_CASES: /html/body/div[2]/div[2]/div[3]/table/tbody/tr[28]/td[2]
    HISPANIC_DEATHS: /html/body/div[2]/div[2]/div[3]/table/tbody/tr[42]/td[2]
    NATIVE_HAWAIIAN_PACIFIC_ISLANDER_CASES: /html/body/div[2]/div[2]/div[3]/table/tbody/tr[29]/td[2]
    NATIVE_HAWAIIAN_PACIFIC_ISLANDER_DEATHS: /html/body/div[2]/div[2]/div[3]/table/tbody/tr[43]/td[2]
    WHITE_CASES: /html/body/div[2]/div[2]/div[3]/table/tbody/tr[30]/td[2]
    WHITE_DEATHS: /html/body/div[2]/div[2]/div[3]/table/tbody/tr[44]/td[2]
    OTHER_CASES: /html/body/div[2]/div[2]/div[3]/table/tbody/tr[31]/td[2]
    OTHER_DEATHS: /html/body/div[2]/div[2]/div[3]/table/tbody/tr[45]/td[2]
  '2020-07-24':
    AMERICAN_INDIAN_OR_ALASKA_NATIVE_CASES: /html/body/div[2]/div[2]/div[2]/table/tbody/tr[29]/td[2]
    AMERICAN_INDIAN_OR_ALASKA_NATIVE_DEATHS: /html/body/div[2]/div[2]/div[2]/table/tbody/tr[43]/td[2]
    ASIAN_CASES: /html/body/div[2]/div[2]/div[2]/table/tbody/tr[30]/td[2]
    ASIAN_DEATHS: /html/body/div[2]/div[2]/div[2]/table/tbody/tr[44]/td[2]
    BLACK_CASES: /html/body/div[2]/div[2]/div[2]/table/tbody/tr[31]/td[2]
    BLACK_DEATHS: /html/body/div[2]/div[2]/div[2]/table/tbody/tr[45]/td[2]
    HISPANIC_CASES: /html/body/div[2]/div[2]/div[2]/table/tbody/tr[32]/td[2]
    HISPANIC_DEATHS: /html/body/div[2]/div[2]/div[2]/table/tbody/tr[46]/td[2]
    NATIVE_HAWAIIAN_PACIFIC_ISLANDER_CASES: /html/body/div[2]/div[2]/div[2]/table/tbody/tr[33]/td[2]
    NATIVE_HAWAIIAN_PACIFIC_ISLANDER_DEATHS: /html/body/div[2]/div[2]/div[2]/table/tbody/tr[47]/td[2]
    WHITE_CASES: /html/body/div[2]/div[2]/div[2]/table/tbody/tr[34]/td[2]
    WHITE_DEATHS: /html/body/div[2]/div[2]/div[2]/table/tbody/tr[48]/td[2]
    OTHER_CASES: /html/body/div[2]/div[2]/div[2]/table/tbody/tr[35]/td[2]
    OTHER_DEATHS: /html/body/div[2]/div[2]/div[2]/table/tbody/tr[49]/td[2]
  '2020-08-01':
    AMERICAN_INDIAN_OR_ALASKA_NATIVE_CASES: /html/body/div[2]/div[2]/div[2]/table[1]/tbody[6]/tr[1]/td[2]
    AMERICAN_INDIAN_OR_ALASKA_NATIVE_DEATHS: /html/body/div[2]/div[2]/div[2]/table[1]/tbody[8]/tr[1]/td[2]
    ASIAN_CASES: /html/body/div[2]/div[2]/div[2]/table[1]/tbody[6]/tr[2]/td[2]
    ASIAN_DEATHS: /html/body/div[2]/div[2]/div[2]/table[1]/tbody[8]/tr[2]/td[2]
    BLACK_CASES: /html/body/div[2]/div[2]/div[2]/table[1]/tbody[6]/tr[3]/td[2]
    BLACK_DEATHS: /html/body/div[2]/div[2]/div[2]/table[1]/tbody[8]/tr[3]/td[2]
    HISPANIC_CASES: /html/body/div[2]/div[2]/div[2]/table[1]/tbody[6]/tr[4]/td[2]
    HISPANIC_DEATHS: /html/body/div[2]/div[2]/div[2]/table[1]/tbody[8]/tr[4]/td[2]
    NATIVE_HAWAIIAN_PACIFIC_ISLANDER_CASES: /html/body/div[2]/div[2]/div[2]/table[1]/tbody[6]/tr[5]/td[2]
    NATIVE_HAWAIIAN_PACIFIC_ISLANDER_DEATHS: /html/body/div[2]/div[2]/div[2]/table[1]/tbody[8]/tr[5]/td[2]
    WHITE_CASES: /html/body/div[2]/div[2]/div[2]/table[1]/tbody[6]/tr[6]/td[2]
    WHITE_DEATHS: /html/body/div[2]/div[2]/div[2]/table[1]/tbody[8]/tr[6]/td[2]
    OTHER_CASES: /html/body/div[2]/div[2]/div[2]/table[1]/tbody[6]/tr[7]/td[2]
    OTHER_DEATHS: /html/body/div[2]/div[2]/div[2]/table[1]/tbody[8]/tr[7]/td[2]
  '2020-08-12':
    AMERICAN_INDIAN_OR_ALASKA_NATIVE_CASES: /html/body/div[2]/div/div[2]/table[1]/tbody[6]/tr[1]/td[2]
    AMERICAN_INDIAN_OR_ALASKA_NATIVE_DEATHS: /html/body/div[2]/div/div[2]/table[1]/tbody[8]/tr[1]/td[2]
    ASIAN_CASES: /html/body/div[2]/div/div[2]/table[1]/tbody[6]/tr[2]/td[2]
    ASIAN_DEATHS: /html/body/div[2]/div/div[2]/table[1]/tbody[8]/tr[2]/td[2]
    BLACK_CASES: /html/body/div[2]/div/div[2]/table[1]/tbody[6]/tr[3]/td[2]
    BLACK_DEATHS: /html/body/div[2]/div/div[2]/table[1]/tbody[8]/tr[3]/td[2]
    HISPANIC_CASES: /html/body/div[2]/div/div[2]/table[1]/tbody[6]/tr[4]/td[2]
    HISPANIC_DEATHS: /html/body/div[2]/div/div[2]/table[1]/tbody[8]/tr[4]/td[2]
    NATIVE_HAWAIIAN_PACIFIC_ISLANDER_CASES: /html/body/div[2]/div/div[2]/table[1]/tbody[6]/tr[5]/td[2]
    NATIVE_HAWAIIAN_PACIFIC_ISLANDER_DEATHS: /html/body/div[2]/div/div[2]/table[1]/tbody[8]/tr[5]/td[2]
    WHITE_CASES: /html/body/div[2]/div/div[2]/table[1]/tbody[6]/tr[6]/td[2]
    WHITE_DEATHS: /html/body/div[2]/div/div[2]/table[1]/tbody[8]/tr[6]/td[2]
    OTHER_CASES: /html/body/div[2]/div/div[2]/table[1]/tbody[6]/tr[7]/td[2]
    OTHER_DEATHS: /html/body/div[2]/div/div[2]/table[1]/tbody[8]/tr[7]/td[2]